### ISSUE TITLE
addIfAbsent does not compare modules correctly

### ISSUE THREAD

**Issue by moarcaffeine** [davidje13/neutrino-typescript#2]
This is related to #1.

I can indeed run your example but I get complaints about @babel/core being missing as a peer dependency of all the dependencies in neutrino-typescript.

Consequently it would seem Babel is not operational in this state. However, when you add @babel/core you will receive the error about duplicate plugins and be unable to proceed to the web landing:

<details>
<summary>Details</summary>

Failed to compile.

./src/index.tsx
Module build failed (from ./node_modules/.pnpm/registry.npmjs.org/babel-loader/8.0.6_@babel+core@7.7.4+webpack@4.41.2/node_modules/babel-loader/lib/index.js):
Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

....
</details>

I traced down the issue and it looks like the fix is relatively simple. I'm attaching a PR. Hope it helps. Thank you for working on this!

**Comment by davidje13** [comment]
I think the main problem here was version mismatches; I have updated all the dependency versions and things seem to be happy (no complaints about @babel/core that I can see). You should never need to explicitly bring in @babel/core in a neutrino project as I understand things (jest, node, and react presets all include it as a non-peer dependency, for example)

I've merged your suggested fix too, since it seems reasonable, but I made a few changes in line with the comments I added to the PR. Can you check that it works for you now?

**Comment by davidje13** [comment]
@moarcaffeine is this OK to close now?

**Comment by davidje13** [comment]
Closing this issue because this appears to be OK and haven't heard back for nearly a year. Happy to re-open if this is still a problem for anybody.
